name: Godbolt C/C++ CI

on:
  push:
    branches:
      - main
  schedule:
    # Every sunday
    - cron:  '0 0 * * 0'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build preprocessed header
      run: echo "#pragma once" && ./scripts/generate_header.sh >> result.hpp
    - uses: actions/upload-artifact@v1
      with:
          name: output
          path: result.hpp

  header:
    runs-on: ubuntu-latest
    needs: [preprocess]
    steps:
    - uses: actions/checkout@v1
      with:
        ref: godbolt
    - uses: actions/download-artifact@v1
      with:
          name: output
    - name: godbolt header
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        mv output/result.hpp godbolt.hpp
        git add godbolt.hpp
        git commit -m "Update godbolt header" || exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: godbolt
        github_token: ${{ secrets.GITHUB_TOKEN }}
